apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mc9u94lkh-nodejs
  janus-idp.io/tekton: mc9u94lkh-nodejs
  backstage.io/kubernetes-id: mc9u94lkh-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mc9u94lkh-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
