apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mc9u94lkh-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mc9u94lkh-nodejs 
  name: mc9u94lkh-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: mc9u94lkh-nodejs 
